name: Publish
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: Configure registry auth
        run: |
          echo "@valentinusz:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages
        run: pnpm run packages:publish
