name: 'Verify'

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: Format check
        run: pnpm run fmt:check

      - name: Lint check
        run: pnpm run lint:check

      - name: TypeScript check
        run: pnpm run typescript:check
